version: "3"
services:
  api:
    image: node
    ports:
      - 3000:3000
    volumes: 
      - .:/src
    working_dir: /src
    command: tail -f /dev/null
    command: bash -c "npm install && npm start"